title: Avaluo Backend
remote_theme: just-the-docs/just-the-docs
description: Documentacion oficial del backend de Avaluo — sistema de gestion de avaluo de desempeno universitario.
color_scheme: dark
search_enabled: true

# Links auxiliares
aux_links:
  "GitHub":
    - "https://github.com/RayfelO/AvaluoBackend"
aux_links_new_tab: true

# Navegacion
heading_anchors: true
nav_sort: case_insensitive

# GitHub Pages
url: "https://RayfelO.github.io"
baseurl: "/AvaluoBackend"

# Footer
footer_content: "Avaluo Backend &copy; 2025"
